/**
 * Server-side accessor for the generated poster metadata sidecar
 * (dynamic accent color + micro blur data URI per poster asset).
 *
 * The JSON file is generated by the CLI (`backfill-poster-meta`, and on
 * every poster processed) and is private content like the posters
 * themselves — the glob keeps its absence a graceful no-op so the
 * public repo still builds.
 */

export interface PosterMeta {
	accent: string;
	blur: string;
}

const modules = import.meta.glob('./poster-meta.json', { eager: true });
const metaMap: Record<string, PosterMeta> =
	(Object.values(modules)[0] as { default?: Record<string, PosterMeta> } | undefined)?.default ??
	{};

/**
 * Look up metadata for a poster path like `/posters/{assetId}.avif`.
 */
export function getPosterMeta(posterPath: string): PosterMeta | undefined {
	const match = posterPath.match(/\/posters\/([^/]+)\.avif$/i);
	if (!match) return undefined;
	return metaMap[match[1]];
}
